services:
  research-agent-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: research-agent-server
    ports:
      - "8080:8080"
    environment:
      - MCP_WEB_URL=http://mcp-server:8080
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - research-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  research-network:
    external: true